name: Build

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.21.x]
        os: [linux, darwin, windows]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
      - name: Extract project version
        id: project_version
        run: echo "::set-output name=version::$(grep 'const version =' colorexp.go | cut -d '"' -f 2)"
      - name: Extract commit hash
        id: git_commit
        run: echo "::set-output name=sha::$(git rev-parse --short HEAD)"
      - name: Download dependencies
        run: go mod tidy
      - name: Build
        run: |
          env GOOS=${{ matrix.os }} GOARCH=amd64 go build -o colorexp-${{ matrix.os }}-amd64-${{ steps.project_version.outputs.version }}-${{ steps.git_commit.outputs.sha }} colorexp.go
      - name: Upload artifact
        if: github.event_name == 'push'
        uses: actions/upload-artifact@v4
        with:
          name: colorexp-${{ matrix.os }}-amd64-${{ steps.project_version.outputs.version }}-${{ steps.git_commit.outputs.sha }}
          path: colorexp-${{ matrix.os }}-amd64-${{ steps.project_version.outputs.version }}-${{ steps.git_commit.outputs.sha }}
